"""Runtime contracts package for Phase 0 autonomous agent interfaces."""

from .contracts import (
    ConflictResolutionPath,
    DangerousCommandSignal,
    ExecutionPlanStep,
    L1ExecutionPlan,
    LifecycleTransitionError,
    MasterLifecycleTransitionError,
    MasterOrchestratorState,
    MasterOrchestratorStateMachine,
    MasterStateTransitionRecord,
    PolicyAuditEvent,
    PolicyDecision,
    PolicyEffect,
    PolicyInterface,
    PolicyRule,
    PlanConfirmationGate,
    PlanConfirmationStatus,
    ResourceTier,
    RuntimeExecutionMode,
    RuntimeHealthSnapshot,
    RuntimeLoopBudget,
    RuntimeLoopState,
    RuntimeRequestEnvelope,
    StopReason,
    TaskLifecycle,
    TaskState,
    ToolContract,
    ToolParameterSpec,
    ToolRiskTier,
    phase0_interface_snapshot,
)
from .safety import (
    DangerousCommandClassifier,
    PermissionQueue,
    PermissionRequest,
    PermissionStatus,
    SafeToolRuntime,
    SafeToolRuntimeResult,
)
from .approval_executor import ApprovalExecutionWorker
from .master_orchestrator import MasterOrchestratorService
from .retry import RetryMatrix, RetryPolicy, RetrySource
from .task_manager import RuntimeTask, RuntimeTaskEvent, RuntimeTaskManager
from .trace_analytics import build_trace_analytics
from .tool_catalog import build_core_tool_catalog, build_core_tool_catalog_dicts
from .event_bus import RuntimeEvent, RuntimeEventBus, runtime_events
from .permission_gate import PermissionCheckResult, PermissionGate, permission_gate
from .health_governor import DeviceHealthSnapshot, RuntimeHealthGovernor, runtime_health_governor
from .session_manager import RuntimeSession, RuntimeSessionManager, runtime_session_manager
from .trace import (
    RuntimeTraceBuffer,
    RuntimeTraceEvent,
    new_message_id,
    new_session_id,
    new_trace_id,
    runtime_trace_buffer,
)

__all__ = [
    "ConflictResolutionPath",
    "DangerousCommandSignal",
    "ExecutionPlanStep",
    "L1ExecutionPlan",
    "LifecycleTransitionError",
    "MasterLifecycleTransitionError",
    "MasterOrchestratorState",
    "MasterOrchestratorStateMachine",
    "MasterStateTransitionRecord",
    "PolicyAuditEvent",
    "PolicyDecision",
    "PolicyEffect",
    "PolicyInterface",
    "PolicyRule",
    "PlanConfirmationGate",
    "PlanConfirmationStatus",
    "ResourceTier",
    "RuntimeExecutionMode",
    "RuntimeHealthSnapshot",
    "RuntimeLoopBudget",
    "RuntimeLoopState",
    "RuntimeRequestEnvelope",
    "StopReason",
    "TaskLifecycle",
    "TaskState",
    "ToolContract",
    "ToolParameterSpec",
    "ToolRiskTier",
    "DangerousCommandClassifier",
    "PermissionQueue",
    "PermissionRequest",
    "PermissionStatus",
    "SafeToolRuntime",
    "SafeToolRuntimeResult",
    "ApprovalExecutionWorker",
    "MasterOrchestratorService",
    "RetryMatrix",
    "RetryPolicy",
    "RetrySource",
    "RuntimeTask",
    "RuntimeTaskEvent",
    "RuntimeTaskManager",
    "RuntimeEvent",
    "RuntimeEventBus",
    "runtime_events",
    "PermissionCheckResult",
    "PermissionGate",
    "permission_gate",
    "DeviceHealthSnapshot",
    "RuntimeHealthGovernor",
    "runtime_health_governor",
    "RuntimeSession",
    "RuntimeSessionManager",
    "runtime_session_manager",
    "RuntimeTraceBuffer",
    "RuntimeTraceEvent",
    "new_message_id",
    "new_session_id",
    "new_trace_id",
    "runtime_trace_buffer",
    "build_trace_analytics",
    "build_core_tool_catalog",
    "build_core_tool_catalog_dicts",
    "phase0_interface_snapshot",
]
